### ISSUE TITLE
Crear login / registro de Supplier (proveedor) tarea004

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#15]
Crear una vista sencilla, utilizando Bootstrap como plantilla de estilos

**Comment by PaoSotomayor** [comment]
Puedo colaborar, ayudar, lo que sea... :)

**Comment by eduardomartsanch** [comment]
ok aqui vamos

**Comment by marioRobledo37** [comment]
ok! para mañana creo poder tenerla!

**Comment by ProyectoTeam5** [comment]
Si lo van. Subir no se olviden de crearse una rama 😊
