### ISSUE TITLE
Crear vista de búsqueda de Suppliers (proveedores) tarea003

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#16]
Vista sencilla, utilizando Bootstrap como platillo de estilo!
Chequear los comentarios que dejé en Figma

**Comment by PaoSotomayor** [comment]
Puedo colaborar, ayudar, lo que sea... :)

**Comment by sanjuandevmx** [comment]
Tarea recibida, comenzare a trabajar en ella mañana por la mañana, espero que tenerla lista al medio dia hora del centro de mexico.
