### ISSUE TITLE
Feedback de la imagen del barco. Hoy antes de la reunión!

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#31]
Ver la imagen del barco que pasó Lau en Discord
Completar y enviar a lau en formato de texto
GOAL: 
RISK: 
IMPEDIMENT: 
HELP:

Ejemplo (El objetivo - GOAL: cumplir con las tareas asignadas y las responsabilidades
Que factor puede arruinar mi objetivo - RISK:   La comunicacion
que puede retrasar mi objetivo - IMPEDIMENT: Escaso conocimiento de algunas herramientas
que me ayudaria a lograr mi objetivo - HELP:  entender mejor thymeleaf)

Ver en Discord los mensajes de los demás integrantes del equipo, así no se repiten los items a agregar

**Comment by marioRobledo37** [comment]
DONE!

**Comment by PaoSotomayor** [comment]
Done!

**Comment by LaureanoCid** [comment]
Done!

**Comment by Dorysfer** [comment]
Listo!
