### ISSUE TITLE
CRUD de usuario

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#36]

**Comment by ProyectoTeam5** [comment]
Tarea recibida 😊
(Soy Cami)

**Comment by ProyectoTeam5** [comment]
Ya tengo el código terminado. Solo me falta probarlo en el postman

**Comment by Dorysfer** [comment]
Tengo el Crud listo, tengo un peque problema en un builder pero está hecho, no lo subo por ello.

**Comment by ProyectoTeam5** [comment]
Terminada.
