### ISSUE TITLE
Usuario en React

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#37]
para poder hacer el CRUD y el listado de usuarios

**Comment by PaoSotomayor** [comment]
@eduardomartsanch Registrarse como USUARIO
@marioRobledo37 Listado de  USUARIOS

no agregar estilos en los archivos css
Sólo agregar en el index.html el link a simplecss:
link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"
Les recuerdo que este link va antes del title

**Comment by PaoSotomayor** [comment]
Hice un nuevo commit en el front con las rutas agregadas para las 3 vistas necesarias. También agregué un Header provisiorio y un estilo básico al App.css

**Comment by PaoSotomayor** [comment]
Por favor, no suban nada a mi rama hasta no chequear todo! Gracias

**Comment by marioRobledo37** [comment]
ok Pao,
