### ISSUE TITLE
Login de User y Supplier en React

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#38]
Teniendo en cuanta que va a estar implementado Spring Security en el back

**Comment by PaoSotomayor** [comment]
Hay un nuevo proyecto armado en git, este contiene la parte de react. Armate una rama que se desprenda de la mía. Mañana vamos a hacer pruebas para organizarnos mejor

**Comment by sanjuandevmx** [comment]
Enterado, nos vemos mas tarde por la mañana.

**Comment by PaoSotomayor** [comment]
Ten en cuenta que a lo largo del día trataré de subir algunas modificaciones en mi rama....

**Comment by PaoSotomayor** [comment]
no agregar estilos en los archivos css
Sólo agregar en el index.html el link a simplecss:
link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"
Les recuerdo que este link va antes del title

**Comment by PaoSotomayor** [comment]
Hice un nuevo commit en el front con las rutas agregadas para las 3 vistas necesarias. También agregué un Header provisiorio y un estilo básico al App.css

**Comment by sanjuandevmx** [comment]
Tarea completada

**Comment by PaoSotomayor** [comment]
Tarea completada, pero en proceso de revisión
