### ISSUE TITLE
crear repositorios con las clases existentes para un primer CRUD básico tarea001

### ISSUE THREAD

**Issue by PaoSotomayor** [ProyectoTeam5/Proyecto-final#9]
Fran, chequear las clases creadas y ver de implementar un CRUD básico

**Comment by ProyectoTeam5** [comment]
Yo me sumo a ayudarte!!! Así vemos si lo dejamos para hoy!! Mándame mensaje al discord y entro

**Comment by PaoSotomayor** [comment]
Yo me sumo también, por si necesitan alguna ayuda!

**Comment by ProyectoTeam5** [comment]
@JesusNjo cuando lo suba no te olvides de crear una rama 😊

**Comment by ProyectoTeam5** [comment]
Ya no pasa nada jaja acabo de ver tu pull request.

**Comment by ProyectoTeam5** [comment]
Repositorio y dao completado! 
Creo que se puede cerrar esta tarea tambien
